In [1]:
import numpy as np

In [2]:
# How to create an empty and a full NumPy array?
empty = np.array([])
empty

array([], dtype=float64)

In [3]:
fullarr = np.array([[1,2,3],[4,5,6],[7,8,9]])
fullarr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
# Create a Numpy array filled with all zeros
zeros = np.zeros((3,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [7]:
# Create a Numpy array filled with all ones
print(np.ones((3,3)))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
# Check whether a Numpy array contains a specified row
