# Array manipulation

# Changing Shape

In [1]:
import numpy as np

In [2]:
a=np.arange(8).reshape(2,4)
print(a)

[[0 1 2 3]
 [4 5 6 7]]


In [3]:
b=a.reshape(2,2,2)
print(b)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [4]:
np.rollaxis(b,1,2)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [5]:
a.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7])

In [6]:
a.flatten("c")

array([0, 1, 2, 3, 4, 5, 6, 7])

In [7]:
a.flatten("f")

array([0, 4, 1, 5, 2, 6, 3, 7])

In [8]:
print(a)

[[0 1 2 3]
 [4 5 6 7]]


# Iterator

In [9]:
a=a=np.arange(0,45,5)

In [10]:
print(a)

[ 0  5 10 15 20 25 30 35 40]


In [11]:
a=a.reshape(3,3)

In [12]:
print(a)

[[ 0  5 10]
 [15 20 25]
 [30 35 40]]


In [13]:
for i in a.flat:
    print(i)

0
5
10
15
20
25
30
35
40


In [14]:
for i in np.nditer(a):
    print(i)

0
5
10
15
20
25
30
35
40


  # Iteration order in C and F style languages

In [15]:
for i in np.nditer(a,order="c"):
    print(i)

0
5
10
15
20
25
30
35
40


In [16]:
for i in np.nditer(a,order="F"):
    print(i)

0
15
30
5
20
35
10
25
40


# joining Arrays

In [17]:
a=np.array([[1,2],[3,4]])
print(a)
b=np.array([[5,6],[7,8]])
print(b)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [18]:
c=np.concatenate((a,b))
print(c)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [19]:
c.ndim

2

In [20]:
d=np.concatenate((a,b), axis=1)
print(d)

[[1 2 5 6]
 [3 4 7 8]]


In [21]:
d.ndim

2

# Splitting arrays

In [22]:
 a=np.arange(9)
print(a)
a.ndim

[0 1 2 3 4 5 6 7 8]


1

In [27]:
b=np.split(a,3)
print(b)
c=np.array(b)
print(c)
c.shape

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


(3, 3)

In [24]:
print(np.split(a,[4,5,7]))

[array([0, 1, 2, 3]), array([4]), array([5, 6]), array([7, 8])]


In [25]:
print(np.split(a,[3,6]))

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]


# Resizing Array