In [1]:
import numpy as np

In [2]:
a=np.array([(1,2,3),(4,5,6)])
print(a)
a.ndim

[[1 2 3]
 [4 5 6]]


2

In [3]:
b=np.linspace(0,5,12)
print(b)

[0.         0.45454545 0.90909091 1.36363636 1.81818182 2.27272727
 2.72727273 3.18181818 3.63636364 4.09090909 4.54545455 5.        ]


In [4]:
print(a.sum(axis = 0))
print(a)

[5 7 9]
[[1 2 3]
 [4 5 6]]


In [5]:
# squre root and std daviation
print(np.sqrt(a))

[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]


In [6]:
print(np.std(a))

1.707825127659933


In [7]:
np.ravel(a)

array([1, 2, 3, 4, 5, 6])

In [10]:
print(np.log10(a))
print(np.log2(a))

[[0.         0.30103    0.47712125]
 [0.60205999 0.69897    0.77815125]]
[[0.         1.         1.5849625 ]
 [2.         2.32192809 2.5849625 ]]


 # Numpy Practice Example


In [9]:
import numpy as np
from matplotlib import pyplot as pt

In [22]:
a=np.array([[3,2,5,5],[6,8,4,5],[9,2,87,4],[1,0,54,3]])
print(a)
print('==========================================')
print(np.sort(a,axis=0))
print('==========================================')

print(np.sort(a,axis=1))


[[ 3  2  5  5]
 [ 6  8  4  5]
 [ 9  2 87  4]
 [ 1  0 54  3]]
[[ 1  0  4  3]
 [ 3  2  5  4]
 [ 6  2 54  5]
 [ 9  8 87  5]]
[[ 2  3  5  5]
 [ 4  5  6  8]
 [ 2  4  9 87]
 [ 0  1  3 54]]


In [41]:
a=np.arange(9).reshape(3,3)
b=np.arange(9).reshape(3,3)
print(a.ndim)
print(np.append(a,b))
print('============================')
print(np.concatenate((a,b),axis=1))
print('============================')

print(np.reshape(a,newshape=(9),order='C'))


2
[0 1 2 3 4 5 6 7 8 0 1 2 3 4 5 6 7 8]
[[0 1 2 0 1 2]
 [3 4 5 3 4 5]
 [6 7 8 6 7 8]]
[0 1 2 3 4 5 6 7 8]


# converting 1D array to 2D array (Add a new axis in the array)

In [61]:
a=np.arange(6) # 1D
print(a)
print(a.shape,a.ndim)
b=a[np.newaxis,:]
print(b)
print(b.shape,b.ndim)
c=b[:,np.newaxis]
print(c)
print(c.shape,c.ndim)

[0 1 2 3 4 5]
(6,) 1
[[0 1 2 3 4 5]]
(1, 6) 2
[[[0 1 2 3 4 5]]]
(1, 1, 6) 3


In [67]:
a=np.arange(6)
b=np.expand_dims(a,axis=0)
print(b,b.ndim,b.shape)

[[0 1 2 3 4 5]] 2 (1, 6)
