# Array Creation

In [1]:
import numpy as np

In [2]:
a=np.array([[2,1,6],[0,4,5]],dtype=np.int32)  # Array creation

In [3]:
a.shape

(2, 3)

In [4]:
a.dtype

dtype('int32')

In [5]:
a.size

6

In [6]:
a.itemsize  # return a specific element size

4

In [7]:
b=np.arange(12)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [8]:
b.reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [9]:
c=np.zeros((2,4))
c

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
c=np.ones((5,6))
c

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [11]:
d=np.array(np.arange(12)).reshape(3,4)
d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [12]:
np.linspace(0,5,12)

array([0.        , 0.45454545, 0.90909091, 1.36363636, 1.81818182,
       2.27272727, 2.72727273, 3.18181818, 3.63636364, 4.09090909,
       4.54545455, 5.        ])

In [13]:
np.empty((3,4))

array([[0.        , 0.45454545, 0.90909091, 1.36363636],
       [1.81818182, 2.27272727, 2.72727273, 3.18181818],
       [3.63636364, 4.09090909, 4.54545455, 5.        ]])

In [14]:
np.empty_like(d)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [15]:
e=np.identity(3)
e

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
e.ndim

2

In [17]:
f=np.array([[0,1,2],[3,4,5]])
f

array([[0, 1, 2],
       [3, 4, 5]])

In [18]:
print(a)

[[2 1 6]
 [0 4 5]]


In [19]:
a.argmax() #return the index number of the maximum element 

2

In [20]:
a.argmin()  #return the index number of the minimum element

3

In [21]:
a.max()  #return the maximum value

6

In [22]:
a.min()  #return the minimum value

0

In [23]:
a.sort()   # sort the array based on the rows 
print(a)   # sort the array rows

[[1 2 6]
 [0 4 5]]


In [24]:
a.argsort()  # sort the array rows and return their index number

array([[0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [25]:
a.transpose()  # same as a.T   # convert the rows into column and column into rows  (T = transpose) 

array([[1, 0],
       [2, 4],
       [6, 5]])

In [26]:
for i in a.flat:
    print(i)

1
2
6
0
4
5


In [27]:
a.nbytes

24

In [28]:
a.argmax(axis=0)

array([0, 1, 0], dtype=int64)

In [29]:
a.argmin(axis=1)


array([0, 0], dtype=int64)

In [30]:
print(a)

[[1 2 6]
 [0 4 5]]


In [31]:
print(a+a)

[[ 2  4 12]
 [ 0  8 10]]


In [32]:
print(a*a)
print(a**a)

[[ 1  4 36]
 [ 0 16 25]]
[[    1     4 46656]
 [    1   256  3125]]


In [33]:
print(a/a)   # 0/0 than error occure

[[ 1.  1.  1.]
 [nan  1.  1.]]


C:\Users\patan\AppData\Local\Temp\ipykernel_23152\1622552695.py:1: RuntimeWarning: invalid value encountered in divide
  print(a/a)   # 0/0 than error occure


In [34]:
print(a%a)

[[0 0 0]
 [0 0 0]]


C:\Users\patan\AppData\Local\Temp\ipykernel_23152\4209166602.py:1: RuntimeWarning: divide by zero encountered in remainder
  print(a%a)


In [35]:
np.sqrt(a)

array([[1.        , 1.41421356, 2.44948974],
       [0.        , 2.        , 2.23606798]])

In [36]:
a.sum()

18

In [37]:
print(np.where(a>7))

(array([], dtype=int64), array([], dtype=int64))


In [38]:
print(np.argwhere(a>7))

[]


In [39]:
print(a)

[[1 2 6]
 [0 4 5]]


In [40]:
z=np.array([[1,2,3,0],[0,4,6,3],[2,4,0,4]])
print(z)

[[1 2 3 0]
 [0 4 6 3]
 [2 4 0 4]]


In [41]:
np.count_nonzero(z)

9

In [42]:
print(z[0,3])

0


In [43]:
print(np.nonzero(z))

(array([0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int64), array([0, 1, 2, 1, 2, 3, 0, 1, 3], dtype=int64))


In [44]:
f.ravel()

array([0, 1, 2, 3, 4, 5])

In [45]:
f.flatten("f")  # search on internet

array([0, 3, 1, 4, 2, 5])


# Numpy with Strings

In [46]:
np.char.add(["hello","ok"],["hyy","k"])

array(['hellohyy', 'okk'], dtype='<U8')

In [47]:
np.char.capitalize("p")

array('P', dtype='<U1')

In [48]:
print(np.char.upper("i  Python"))

I  PYTHON


In [49]:
print(np.char.lower("I Python"))

i python


In [50]:
print(np.char.title("i Python"))

I Python


In [51]:
print(np.char.title("I Python"))

I Python


In [52]:
print(np.char.center("i Python",25,fillchar="-"))

---------i Python--------


In [53]:
print(np.char.strip("i Python","i am aashish"))  # remove the character from the first string ending and starting 

Python


In [54]:
print(np.char.split("i Python"))

['i', 'Python']


In [55]:
print(np.char.splitlines(["i Python\n \
i Python"]))

[list(['i Python', ' i Python'])]


In [56]:
print(np.char.splitlines("i Python\n \
i Python"))

['i Python', ' i Python']


In [57]:
print(np.char.replace("i Python","love","adore"))

i Python


In [58]:
print(np.char.join("-","dmy"))

d-m-y


# array arthmetic operation

In [59]:
w=np.arange(9).reshape(3,3)
print(w)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [60]:
q=np.array([10,10,10])
print(q)

[10 10 10]


In [61]:
print(np.add(w,q))

[[10 11 12]
 [13 14 15]
 [16 17 18]]


In [62]:
print(np.subtract(w,q))

[[-10  -9  -8]
 [ -7  -6  -5]
 [ -4  -3  -2]]


In [63]:
print(np.multiply(w,q))

[[ 0 10 20]
 [30 40 50]
 [60 70 80]]


In [64]:
print(np.divide(w,q))

[[0.  0.1 0.2]
 [0.3 0.4 0.5]
 [0.6 0.7 0.8]]


# Slicing

In [65]:
a=np.arange(10)

In [66]:
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [67]:
print(a[5])

5


In [68]:
print(a[5:])

[5 6 7 8 9]


In [69]:
s=slice(0,9,3)


In [70]:
print(a[s])

[0 3 6]


In [71]:
a = np.arange(6).reshape(2,3)
print(a.shape)
print(a)
a2 = a[np.newaxis,]  
print(a2)
a2.shape

(2, 3)
[[0 1 2]
 [3 4 5]]
[[[0 1 2]
  [3 4 5]]]


(1, 2, 3)

In [72]:
m=np.arange(36).reshape(6,6)
m

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [73]:
m.dtype

dtype('int32')

In [74]:
n=m.astype(np.int64)
n

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]], dtype=int64)

In [75]:
m.dtype
n.dtype

dtype('int64')

In [79]:
np.random()
c

TypeError: 'module' object is not callable